### ISSUE TITLE
No trajectory

### ISSUE THREAD

**Issue by lxy-mini** [shanmo/OrcVIO-Stereo-Python#3]
![image](https://user-images.githubusercontent.com/83104728/179344872-5063a8f2-1189-4043-b3f2-f71574b2b54c.png)
excuse me,in viewer ,I can't see the run graph of the trajectory run, but I can see it in your demo；

**Comment by lxy-mini** [comment]
At this point my terminal shows：
/home/zjut/2022_lxy/07/OrcVIO-Stereo-Python/utils.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  [-y, x, 0]])
Start online reset...

**Comment by shanmo** [comment]
I suspect this is not related to the software in this repo, but setup, e.g. dataset, calibration, filepath, etc. Please check the output from the trajectory, maybe some output is `None`. You can start by printing out the variables in https://github.com/shanmo/OrcVIO-Stereo-Python/blob/3902248ab9ea7eeec3826224869d998f0141a553/orcvio.py#L915-L935

**Comment by lxy-mini** [comment]
![image](https://user-images.githubusercontent.com/83104728/179437170-9cd27537-2d43-4737-8876-327c58406b51.png)
Hi, I found that IMU only shows a short track and then nothing after that. At the same time, there is no IMU track output on the terminal.

**Comment by shanmo** [comment]
- Please test first using https://github.com/uoip/stereo_msckf, https://github.com/KumarRobotics/msckf_vio or https://github.com/rpng/open_vins to make sure the dataset setup is correct
- Check the features are detected correctly from images https://github.com/shanmo/OrcVIO-Stereo-Python/blob/3902248ab9ea7eeec3826224869d998f0141a553/orcvio.py#L191-L244
